### PR TITLE
Merge branch-TagEventBugFix-Qiaoran with Master

### LINKED ISSUE #176: [PE-D][Tester A] Unknown error thrown
Under tagEvent, if an index <1 is used, an odd error is thrown instead of informing the user to use an index in the range. 

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: ama-chi/ped#5

### LINKED ISSUE #178: [PE-D][Tester B] Grammer mistake for tagged person in Event
Just a minor bug, "1 people" instead of "1 person"

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: ish1506/ped#6

### PR DESCRIPTION
**Pull request by Qiaoran-M**
Closes #176
Closes #178

### CODE REVIEW

**Comment by Qiaoran-M** [comment]
Invalid index error message and tagged person GUI:
Screenshot 2022-10-31 at 1 54 54 PM

This branch is built on the mailing list UserGuide PR in case the mailing list part in UG gets deleted by this PR.

**Review by Benjamin-Sim — COMMENTED** [review]
LGTM! 👍

But not approving yet since there are changes for the UG in #202. I'll approve and merge this PR once #202 has been merged.

**Review by Benjamin-Sim — COMMENTED** [review]
Now that #202 has been merged, can you merge the `master` branch into this branch so that the user guide will be updated? I don't want to merge it now because this PR will override the changes made in #202.

**Review by Benjamin-Sim — APPROVED** [review]
LGTM! 👍

**Pull request merged**
